#!/usr/bin/env python3
"""Ping IndexNow so today's digest is crawled in minutes rather than days.

Why this and not "submit to more search engines": AIgregator is already indexed
by Google and by Bing (DuckDuckGo, which is Bing-backed, returns our digests).
The remaining problem for a DAILY publication is latency -- a digest that gets
crawled four days late is stale news by the time anyone can find it. IndexNow is
a push protocol: one POST tells Bing, Yandex, Seznam, Naver and the other
participating engines that a URL changed. Google does NOT participate; its
sitemap lastmod is the only lever there.

Ownership is proved by hosting {key}.txt at the site root containing the key.
That file is generated by scripts/build.py from INDEXNOW_KEY below, so the key
and the file cannot drift apart.

Usage:
    python3 tools/indexnow_ping.py                  # today's digest + index
    python3 tools/indexnow_ping.py --urls A B       # explicit URLs
    python3 tools/indexnow_ping.py --dry-run        # print, do not send

Exit codes: 0 on success or a legitimate no-op, 1 on a real failure. Safe to
call from publish.sh -- a failed ping must never fail the publish.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
SITE = "https://aigregator.news"
HOST = "aigregator.news"

# 8-128 hex chars. Public by design (it is served at the site root); it proves
# ownership, it is not a secret. Rotating it means changing this constant and
# rebuilding, which regenerates the key file.
INDEXNOW_KEY = "a7f3c1e94b8d24605fa1c3e78b9d02f4"

# One endpoint is enough: participating engines share submissions with each
# other per the protocol. api.indexnow.org is the neutral front door.
ENDPOINT = "https://api.indexnow.org/indexnow"

TIMEOUT = 20


def todays_urls() -> list[str]:
    """The pages a fresh digest actually changes.

    Deliberately narrow. IndexNow is a "this changed" signal, and submitting the
    whole site every day is how you earn a 429 and get ignored. Note that mtime
    is NOT a usable freshness signal here -- every build rewrites every page, so
    an mtime check matches all 15 weeklies on any rebuild. Use the content date
    encoded in the filename instead, which only advances when a real new page
    is published.
    """
    urls = [f"{SITE}/", f"{SITE}/archive.html"]

    digests = sorted(DOCS.glob("digests/*.html"))
    if digests:
        urls.append(f"{SITE}/digests/{digests[-1].stem}.html")

    # Only push the newest weekly, and only if its ISO week is the current one.
    weeklies = sorted(DOCS.glob("weekly/2026-W*.html"))
    if weeklies:
        newest = weeklies[-1].stem  # e.g. 2026-W35
        iso_year, iso_week, _ = dt.date.today().isocalendar()
        if newest == f"{iso_year}-W{iso_week:02d}":
            urls.append(f"{SITE}/weekly/{newest}.html")
            urls.append(f"{SITE}/weekly/")

    # Preserve order, drop duplicates.
    return list(dict.fromkeys(urls))


def ping(urls: list[str], dry_run: bool = False) -> int:
    if not urls:
        print("indexnow: nothing to submit")
        return 0

    payload = {
        "host": HOST,
        "key": INDEXNOW_KEY,
        "keyLocation": f"{SITE}/{INDEXNOW_KEY}.txt",
        "urlList": urls,
    }

    print(f"indexnow: submitting {len(urls)} URL(s)")
    for u in urls:
        print(f"  {u}")

    if dry_run:
        print("indexnow: --dry-run, not sending")
        return 0

    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        ENDPOINT,
        data=body,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            code = resp.status
    except urllib.error.HTTPError as e:
        code = e.code
    except Exception as e:  # network down, DNS, timeout
        print(f"indexnow: FAILED to reach endpoint: {type(e).__name__}: {e}")
        return 1

    # 200 = accepted, 202 = accepted with key validation pending. Both fine.
    if code in (200, 202):
        print(f"indexnow: OK (HTTP {code})")
        return 0
    meaning = {
        400: "bad request (invalid format)",
        403: "key not valid -- is the key file deployed at the site root?",
        422: "URL does not belong to the host, or key schema mismatch",
        429: "too many requests -- back off",
    }.get(code, "unexpected response")
    print(f"indexnow: FAILED HTTP {code} -- {meaning}")
    return 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--urls", nargs="*", help="explicit URLs (default: today's)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    return ping(args.urls or todays_urls(), dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
